### PR TITLE
Fix compile error trying to extract ?gpb_field record from gpb.hrl

### PR DESCRIPTION
**Pull request by jannekai**
During mix.compile stage the exprotobuf library failed to compile with the following error:

(dev) ➜  ~/s/exprotobuf git:(master) ✗ mix compile
Compiled lib/exprotobuf/encoder.ex
Compiled lib/exprotobuf/utils.ex

== Compilation error on file lib/exprotobuf/field.ex ==
** (ArgumentError) no record ?gpb_field found at /Users/janneka/src/exprotobuf/deps/gpb/include/gpb.hrl
    (elixir) lib/record/extractor.ex:38: Record.Extractor.extract_record/2
    lib/exprotobuf/field.ex:2: (module)
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6

Seems like using :field instead of :"?gdb_field" works and project compiles.

### CODE REVIEW

**Comment by jannekai** [comment]
Hmm, seems like there were build issues, on other elixir releases. The compile failed on OS X build with Erlang 17.5 and Elixir 1.0.5.

**Comment by bitwalker** [comment]
Ah, yeah I was developing on 1.0.4. That's really strange, but I think there were some changes to `Record.Extractor.extract` in 1.0.5. I'll look tonight and fix this.

**Comment by jannekai** [comment]
Yeah, this commit is probably the root cause https://github.com/elixir-lang/elixir/commit/c2bc796e18435c56f267bed73471dabcbeca4e54

I guess the -ifdef clauses are now actually evaluated in 1.0.5 and therefore it will expand the record name as :field instead of :"?gpb_field". No idea how to solve this in backward compatible manner either.

**Comment by bitwalker** [comment]
Yeah that was the change I was thinking of, I think I'll have to check the current version of Elixir at compile time and switch on it to keep this backwards compatible :(

**Comment by bitwalker** [comment]
Fixed in bcd8144c

**Comment by bitwalker** [comment]
Also released as 0.10.1 on hex
